version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies (if needed)..."
      - npm install 
  pre_build:
    commands:
      - echo "Pre-build:Running any preparation tasks..."
  build:
    commands:
      - echo "Build:Running the build process..."
      - echo "No build steps needed for static HTML, skipping."
  post_build:
    commands:
      - echo "Post-build:Preparing artifacts for deployment..."
      - echo "Build process completed."

artifacts:
  files:
    - '**/*' 
  base-directory: '.' 
  discard-paths: no
