version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install for HTML project"
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post-build phase completed"
artifacts:
  files:
    - dynamic.html
